version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - eureka-network

  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - eureka-network

  task-service:
    build: ./task-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - eureka-network

networks:
  eureka-network:
