server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    instance:
      prefer-ip-address: true

spring:
  application:
    name: task-service
